name: netflix_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  image: ^3.2.1
  flutter_screenutil: ^5.8.4
  blur: ^3.0.0
  provider: ^6.0.5
  video_player: ^2.7.2
  flutter_xlider: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/user/
    - assets/watch/
    - assets/icons/
    - assets/video/
    - assets/gif/
  fonts:
    - family: Netflixsans
      fonts:
        - asset: assets/fonts/NetflixSans-Regular.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
